### ISSUE TITLE
Can you kindly share links to other interesting M5  solutions

### ISSUE THREAD

**Issue by Sandy4321** [pedroMoya/M5_kaggle_accuracy_KAGGLE_M5_A_share#1]
Great code thank you very much 
Can you kindly share links to other interesting M5  solutions
Especially what help understand what was done in 
1st place
https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/163684
2nd place
https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/164599
3d place
https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/164374
4th place
https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/163216
7th place
https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/164826
etc..

**Comment by pedroMoya** [comment]
hi, nowadays I'm committed in catch more insights in datascience (MITx micromaster SDS),
but look into https://www.kaggle.com/c/m5-forecasting-accuracy/discussion
and https://www.lancaster.ac.uk/lums/research/areas-of-expertise/centre-for-marketing-analytics-and-forecasting/
and https://scholar.google.es/scholar?hl=es&as_sdt=0,5&q=M5+forecasting&scisbd=1
